# Generated by Django 3.0.3 on 2020-02-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200228_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(choices=[('Abnormal', 'Abnormal'), ('Normal', 'Normal'), ('Unknown', 'Unknown')], max_length=100),
        ),
    ]
