# Generated by Django 3.0.2 on 2020-02-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Abnormal', 'Abnormal'), ('Normal', 'Normal'), ('Unknown', 'Unknown')], max_length=100)),
                ('cover', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
