# Generated by Django 3.0.2 on 2020-03-21 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MachineLearningModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImageLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('model_classification', models.CharField(choices=[('Abnormal', 'Abnormal'), ('Normal', 'Normal'), ('Unknown', 'Unknown')], max_length=100)),
                ('confidence', models.FloatField(default=0.5)),
                ('adjusted_confidence', models.FloatField(default=0)),
                ('image_file', models.ImageField(upload_to='images/')),
                ('abnormal_votes', models.IntegerField(default=0)),
                ('normal_votes', models.IntegerField(default=0)),
                ('unknown_votes', models.IntegerField(default=0)),
                ('machine_learning_model', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='imagelabeling.MachineLearningModel')),
            ],
        ),
    ]
