# Generated by Django 3.0.2 on 2020-02-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagelabel',
            old_name='title',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='imagelabel',
            old_name='cover',
            new_name='image_file',
        ),
    ]
