# Generated by Django 3.0.2 on 2020-03-21 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelabel',
            name='machine_learning_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imagelabeling.MachineLearningModel'),
        ),
    ]
