# Generated by Django 3.0.2 on 2020-02-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0002_auto_20200229_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelabel',
            name='title',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
