# Generated by Django 3.0.2 on 2020-03-21 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0002_auto_20200321_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelabel',
            name='machine_learning_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='imagelabeling.MachineLearningModel'),
            preserve_default=False,
        ),
    ]
