# Generated by Django 3.0.2 on 2020-03-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0003_auto_20200321_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelearningmodel',
            name='classification_notes',
            field=models.CharField(default='placeholder', max_length=100),
            preserve_default=False,
        ),
    ]
