# Generated by Django 3.0.2 on 2020-02-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0004_auto_20200229_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelabel',
            name='confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='imagelabel',
            name='abnormal_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imagelabel',
            name='normal_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imagelabel',
            name='unknown_votes',
            field=models.IntegerField(default=0),
        ),
    ]
