# Generated by Django 3.0.2 on 2020-03-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0004_machinelearningmodel_classification_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagelabel',
            old_name='abnormal_votes',
            new_name='one_votes',
        ),
        migrations.RenameField(
            model_name='imagelabel',
            old_name='normal_votes',
            new_name='zero_votes',
        ),
        migrations.AlterField(
            model_name='imagelabel',
            name='model_classification',
            field=models.CharField(choices=[('1', '1'), ('0', '0'), ('Unknown', 'Unknown')], max_length=100),
        ),
    ]
