# Generated by Django 3.0.2 on 2020-03-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0005_auto_20200229_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelabel',
            name='adjusted_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='imagelabel',
            name='confidence',
            field=models.FloatField(default=0.5),
        ),
    ]
