# Generated by Django 3.0.2 on 2020-04-04 04:38

from django.db import migrations, models
import imagelabeling.models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0006_auto_20200322_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelabel',
            name='image_file',
            field=models.ImageField(upload_to=imagelabeling.models.get_image_filename),
        ),
    ]
