# Generated by Django 3.0.4 on 2020-04-03 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0007_input'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Input',
            new_name='userInput',
        ),
        migrations.RenameField(
            model_name='userinput',
            old_name='r',
            new_name='input',
        ),
    ]
