# Generated by Django 3.0.2 on 2020-04-04 05:00

from django.db import migrations, models
import imagelabeling.models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0009_auto_20200404_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelabel',
            name='image_file',
            field=models.ImageField(upload_to=imagelabeling.models.get_image_filename),
        ),
    ]
