# Generated by Django 3.0.4 on 2020-04-03 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0009_auto_20200403_0323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
