# Generated by Django 3.0.2 on 2020-04-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0010_auto_20200404_0500'),
        ('imagelabeling', '0012_auto_20200404_2038'),
    ]

    operations = [
    ]
