# Generated by Django 3.0.4 on 2020-04-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0012_auto_20200404_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numofiteration',
            name='Iteration',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], max_length=100),
        ),
    ]
