# Generated by Django 3.0.4 on 2020-04-04 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0013_auto_20200404_2306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NumOfIteration',
        ),
    ]
