# Generated by Django 3.0.2 on 2020-04-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0013_merge_20200404_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagelabel',
            old_name='adjusted_confidence',
            new_name='adjusted_user_score',
        ),
        migrations.RenameField(
            model_name='imagelabel',
            old_name='confidence',
            new_name='user_score',
        ),
        migrations.AddField(
            model_name='imagelabel',
            name='model_score',
            field=models.FloatField(default=0),
        ),
    ]
