# Generated by Django 3.0.2 on 2020-04-06 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0015_numofiteration'),
        ('imagelabeling', '0014_auto_20200405_1836'),
    ]

    operations = [
    ]
