# Generated by Django 3.0.2 on 2020-04-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0016_merge_20200406_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelabel',
            name='model_probability',
            field=models.FloatField(default=0),
        ),
    ]
