# Generated by Django 3.0.2 on 2020-04-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0017_imagelabel_model_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelabel',
            name='model_difference',
            field=models.FloatField(default=0),
        ),
    ]
