# Generated by Django 3.0.2 on 2020-04-15 16:18

from django.db import migrations, models
import django.db.models.deletion
import imagelabeling.models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0019_fieldschema_modelschema'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('model_classification', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('Unknown', 'Unknown')], max_length=100)),
                ('user_score', models.FloatField(default=0.5)),
                ('adjusted_user_score', models.FloatField(default=0)),
                ('model_score', models.FloatField(default=0)),
                ('model_difference', models.FloatField(default=0)),
                ('model_probability', models.FloatField(default=0)),
                ('zero_votes', models.IntegerField(default=0)),
                ('one_votes', models.IntegerField(default=0)),
                ('two_votes', models.IntegerField(default=0)),
                ('three_votes', models.IntegerField(default=0)),
                ('four_votes', models.IntegerField(default=0)),
                ('five_votes', models.IntegerField(default=0)),
                ('six_votes', models.IntegerField(default=0)),
                ('seven_votes', models.IntegerField(default=0)),
                ('eight_votes', models.IntegerField(default=0)),
                ('nine_votes', models.IntegerField(default=0)),
                ('unknown_votes', models.IntegerField(default=0)),
                ('image_file', models.ImageField(upload_to=imagelabeling.models.get_image_filename)),
                ('machine_learning_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagelabeling.MachineLearningModel')),
            ],
        ),
    ]
