# Generated by Django 3.0.2 on 2020-04-17 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0020_numberlabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineLearningNumbersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('classification_notes', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='numberlabel',
            name='user_classification',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), ('Unknown', 'Unknown')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='numberlabel',
            name='model_classification',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), ('Unknown', 'Unknown')], max_length=100),
        ),
        migrations.AlterField(
            model_name='numberlabel',
            name='machine_learning_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagelabeling.MachineLearningNumbersModel'),
        ),
    ]
