# Generated by Django 3.0.2 on 2020-04-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0021_auto_20200417_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberlabel',
            name='acute_angle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='numberlabel',
            name='close_eye_hook',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='numberlabel',
            name='curves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='numberlabel',
            name='horizontal_line',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='numberlabel',
            name='loops',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='numberlabel',
            name='open_eye_hook',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='numberlabel',
            name='right_angle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='numberlabel',
            name='shape_options',
            field=models.CharField(choices=[(0, 'Oval'), (1, 'Stick'), (2, 'Swan'), (3, 'Butterfly'), (4, 'Flag'), (5, 'Hook'), (6, 'Combination Clock'), (7, 'Boomerang'), (8, 'Snowman'), (9, 'Balloon on a String')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numberlabel',
            name='vertical_line',
            field=models.IntegerField(default=0),
        ),
    ]
