# Generated by Django 3.0.2 on 2020-04-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0021_numberlabel_user_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberlabel',
            name='model_classification',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), ('Unknown', 'Unknown')], max_length=100),
        ),
        migrations.AlterField(
            model_name='numberlabel',
            name='user_classification',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), ('Unknown', 'Unknown')], max_length=100),
        ),
    ]
