# Generated by Django 3.0.4 on 2020-04-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0024_digitfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitfeature',
            name='loops',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='digitfeature',
            name='total_digit',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
