# Generated by Django 3.0.4 on 2020-04-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0025_auto_20200421_0442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.AddField(
            model_name='digitfeature',
            name='acute_Angle',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='digitfeature',
            name='close_eye_hook',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='digitfeature',
            name='curve',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='digitfeature',
            name='horizontal_line',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='digitfeature',
            name='open_eye_hook',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='digitfeature',
            name='right_Angle',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='digitfeature',
            name='vertical_line',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
