# Generated by Django 3.0.4 on 2020-04-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0026_auto_20200421_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitfeature',
            name='acute_Angle',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='digitfeature',
            name='close_eye_hook',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='digitfeature',
            name='curve',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='digitfeature',
            name='horizontal_line',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='digitfeature',
            name='loops',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='digitfeature',
            name='open_eye_hook',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='digitfeature',
            name='right_Angle',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='digitfeature',
            name='total_digit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='digitfeature',
            name='vertical_line',
            field=models.IntegerField(null=True),
        ),
    ]
