# Generated by Django 3.0.4 on 2020-04-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0027_auto_20200421_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitfeature',
            name='label',
            field=models.IntegerField(null=True),
        ),
    ]
