# Generated by Django 3.0.2 on 2020-04-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0028_digitfeature_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitfeature',
            name='curve',
        ),
    ]
