# Generated by Django 3.0.4 on 2020-04-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0029_remove_digitfeature_curve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alpha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha', models.FloatField(default=0)),
            ],
        ),
    ]
