# Generated by Django 3.0.4 on 2020-04-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0031_auto_20200429_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alpha',
            name='alpha',
            field=models.FloatField(null=True),
        ),
    ]
