# Generated by Django 3.0.4 on 2020-04-29 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0032_auto_20200429_0445'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alpha',
            new_name='AlphaInput',
        ),
        migrations.RenameField(
            model_name='alphainput',
            old_name='alpha',
            new_name='alpha_input',
        ),
    ]
