# Generated by Django 3.0.4 on 2020-04-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelabeling', '0035_auto_20200429_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alphainput',
            name='alpha_input',
            field=models.FloatField(default=0),
        ),
    ]
